spring:
  application:
    name: Incident-Management-System
  datasource:
    url: jdbc:mysql://localhost:3306/emergency
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 0



#spring:
#  application:
#    name: incident-service
#  config:
#    import:
#      optional: configserver:http://localhost:8887

eureka:
  client:
    registerWithEureka: true        # Registers this service with the Eureka server
    fetchRegistry: true             # Fetches the registry from the Eureka server
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  # URL of the Eureka server to connect with
  instance:
    hostname: localhost             # The hostname of the instance
    instance-id: "${spring.application.name}:${instanceId:${random.value}}"  # Instance ID, with dynamic values

#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
##      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      producer:
#        properties:
#          spring.json.type.mapping: event:com.ust.Incident_Management_System.Model.IncidentReport

#      consumer:
#        properties:
#          spring.json.type.mapping: event:com.ust.Notification_service.IncidentReport
#      properties:
#        spring.json.add.type.headers: true  # Optional: include type information in the headers
#        spring.json.include.type: FULL
#        spring.json.type.mapping: com.ust.Incident_Management_System.Model.IncidentReport
#eureka:
#  client:
#    registerWithEureka: true        # Registers this service with the Eureka server
#    fetchRegistry: true             # Fetches the registry from the Eureka server
#    serviceUrl:
#      defaultZone: http://localhost:8761/  # URL of the Eureka server to connect with
#  instance:
#    hostname: localhost             # The hostname of the instance
#    instance-id: "${spring.application.name}:${instanceId:${random.value}}"  # Instance ID, with dynamic values