spring:
  application:
    name: ApiGateway

  datasource:
    url: jdbc:mysql://localhost:3306/emergency
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Consider changing to 'validate' or 'none' in production
    show-sql: true

  cloud:
    gateway:
      mvc:
        routes:
          - id: lbservice-route1
            uri: lb://COMPLAINTREQUESTSERVICE
            predicates:
              - Path=/api/community/complaint-service/complaints/**
          - id: lbservice-route2
            uri: lb://COMPLAINTREQUESTSERVICE
            predicates:
              - Path=/api/community/complaint-service/vendor/**
          - id: lbservice-route3
            uri: lb://COMPLAINTREQUESTSERVICE
            predicates:
              - Path=/api/community/complaint-service/request/**


          - id: lbservice-route4
            uri: lb://SOCIETYMANAGEMENTSERVICE
            predicates:
              - Path=/api/community/management-service/emergency-contacts/**
          - id: lbservice-route5
            uri: lb://SOCIETYMANAGEMENTSERVICE
            predicates:
              - Path=/api/community/management-service/flats/**
          - id: lbservice-route6
            uri: lb://SOCIETYMANAGEMENTSERVICE
            predicates:
              - Path=/api/community/management-service/parking/**
          - id: lbservice-route7
            uri: lb://SOCIETYMANAGEMENTSERVICE
            predicates:
              - Path=/api/community/management-service/residents/**
          - id: lbservice-route8
            uri: lb://SOCIETYMANAGEMENTSERVICE
            predicates:
              - Path=/api/community/management-service/security-details/**
          - id: lbservice-route9
            uri: lb://SOCIETYMANAGEMENTSERVICE
            predicates:
              - Path=/api/community/management-service/societies/**


          - id: lbservice-route10
            uri: lb://EVENTSUPDATESSERVICE
            predicates:
              - Path=/api/community/event-service/event/**
          - id: lbservice-route11
            uri: lb://EVENTSUPDATESSERVICE
            predicates:
              - Path=/api/community/event-service/feedback/**
          - id: lbservice-route12
            uri: lb://EVENTSUPDATESSERVICE
            predicates:
              - Path=/api/community/event-service/notice/**
          - id: lbservice-route13
            uri: lb://EVENTSUPDATESSERVICE
            predicates:
              - Path=/api/community/event-service/post/**

    discovery:
      enabled: true

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

      instance:
        hostname: localhost
        instance-id: ${spring.application.name}:${instanceId:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9999

#logging:
#  level:
#    org.springframework: DEBUG

#security:
#  jwt:
#    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
#    expiration-time: 86400000
